builders:
  phive:
    target: ""
    import: "package:phive_generator/builder.dart"
    builder_factories: ["phiveBuilder"]
    build_extensions: { ".dart": [".phive.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  phive_auto:
    target: ""
    import: "package:phive_generator/builder.dart"
    builder_factories: ["phiveAutoBuilder"]
    build_extensions: { ".dart": [".phive_auto.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
