name: phive_barrel
description: "Ready-to-use PHive hooks including TTL and encryption helpers."
version: 0.2.1
homepage: https://github.com/Pathverse/phive

environment:
  sdk: ^3.11.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  pointycastle: ^4.0.0
  phive: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
