name: phive_barrel
description: "Concrete Hook implementations for PHive CE generator."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.0
  flutter: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  pointycastle: ^3.9.1
  phive:
    path: ../phive

dev_dependencies:
  flutter_test:
    sdk: flutter
